name       : unifdef
version    : 2.12
release    : 1
source     :
    - https://dotat.at/prog/unifdef/unifdef-2.12.tar.gz : fba564a24db7b97ebe9329713ac970627b902e5e9e8b14e19e024eb6e278d10b
license    : BSD-2-Clause
component  : programming.library
summary    : Remove #ifdef'ed lines
description: |
    Remove #ifdef'ed lines
build      : |
    %make prefix=%PREFIX%
install    : |
    %make_install prefix=%PREFIX%
